language: android
jdk: oraclejdk8

sudo: false

android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-android-support

before_install:
  - openssl aes-256-cbc -K $encrypted_d71df9144721_key -iv $encrypted_d71df9144721_iv
    -in xch_android.jks.enc -out xch_android.jks -d

before_script:
- chmod +x gradlew

script:
- "./gradlew assembleRelease"
