language: android
jdk: oraclejdk8


android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support
    - extra


before_install:


before_script:
  - chmod +x gradlew


script:
  - ./gradlew assembleRelease


deploy:
